[horizon]
text               = fdf0ed
subtext            = fadad1
main               = 1A1C23
sidebar            = 16161c
player             = 16161c
card               = 16161c
shadow             = 16161c
selected-row       = fadad1
button             = e9436f
button-active      = fadad1
button-disabled    = 2E303E
tab-active         = e9436f
notification       = 16161c
notification-error = e9436f
misc               = 16161c

[catppuccin_mocha]
text               = cdd6f4
subtext            = CDD6F4
main               = 1E1E2E
main-elevated      = 313244
highlight          = 313344
highlight-elevated = 45475a
sidebar            = 181825
player             = 11111B
card               = 313244
shadow             = 181825
selected-row       = 9399B2
button             = f38ba8
button-active      = 9399B2
button-disabled    = 6C7086
tab-active         = f38ba8
notification       = 313244
notification-error = F38BA8
equalizer          = 000000
misc               = 45475A

[gruvbox-dark]
; topbar
topbar              = 32302f
topbar-text         = f9f5d7
topbar-subtext      = ebdbb2
tab-active          = 3c3836
tab-active-text     = f9f5d7
tab-hover           = 3c3836
topbar-border       = 282828

; sidebars
sidebar             = 32302f
sidebar-text        = f9f5d7
link-hover-text     = f9f5d7
link-active         = 504945
link-active-text    = f9f5d7
sidebar-border      = 282828

; main view
main                = 3c3836
text                = f9f5d7
subtext             = ebdbb2
selected-row        = d5c4a1

; player bar
player              = 282828
player-text         = f9f5d7
player-subtext      = ebdbb2
player-selected-row = d5c4a1
player-border       = 1d2021

; accent colors
button-active       = d79921

; others
button              = a89984
button-disabled     = 3c3836
scrollbar           = d5c4a1
scrollbar-hover     = d79921
context-menu        = 3c3836
context-menu-text   = f9f5d7
context-menu-hover  = 504945
card                = 504945
shadow              = 0c0c0c
notification        = 202020
notification-error  = d32635
misc                = 959595

; ylx
main-elevated       = 000000
highlight-elevated  = 000000
highlight           = 24273a
