#
# HYPRLAND CONFIG for my dots :]
#

# restore wpgtk config upon launch
exec-once = wal -R
source = ~/.cache/wal/colors-hypr.conf

# outputs
monitor=eDP-1, 1920x1080, 0x0, 1		# laptop display
monitor=,preferred,auto,auto			# fallback config

# wob
$WOBSOCK = $XDG_RUNTIME_DIR/wob.sock
exec-once = rm -f $WOBSOCK 
exec-once = mkfifo $WOBSOCK 
exec-once = tail -f $WOBSOCK | wob

# gsettings
exec = gsettings set org.gnome.desktop.interface gtk-theme 'FlatColor'
exec = gsettings set org.gnome.desktop.interface icon-theme 'Papirus-Dark'
exec = gsettings set org.gnome.desktop.wm.preferences button-layout ':close'
exec = gsettings set org.gnome.desktop.interface cursor-theme 'ArcDusk-cursors'

### WM CONFIG =======================================================

# default env vars.
env = XCURSOR_SIZE,24

input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =

    follow_mouse = 1

    touchpad {
        natural_scroll = true
		disable_while_typing = false
    }

    sensitivity = 0.1 # -1.0 - 1.0, 0 means no modification.

	touchdevice {
		output = eDP-1
	}
}

general {
    gaps_in = 5
    gaps_out = 15
    border_size = 3
    col.active_border = $color_color1 $color_color3 45deg
    col.inactive_border = $color_color0

    layout = dwindle
}

decoration {
    rounding = 5

	blur {
		enabled = true
		size = 3
		passes = 3
	}

    drop_shadow = true
    shadow_range = 4
    shadow_render_power = 3
    col.shadow = rgba(000000af)
}

animations {
    enabled = true

    animation = windows, 1, 5, default
    animation = border, 1, 10, default
    animation = borderangle, 1, 8, default
    animation = fade, 1, 4, default
    animation = workspaces, 1, 3, default
}

dwindle {
    pseudotile = true # master switch for pseudotiling
    preserve_split = true # you probably want this
}

master {
    new_is_master = true
}

gestures {
    workspace_swipe = true
	workspace_swipe_fingers = 3
	workspace_swipe_distance = 500
	workspace_swipe_forever = true
}

# sourced files =====================================================
source = ~/.config/hypr/rules.conf
source = ~/.config/hypr/keybinds.conf
source = ~/.config/hypr/startup.conf
