#
# HYPRLAND CONFIG for my dots :]
#

# restore pywal config upon launch
exec-once = wal -R
source = ~/.cache/wal/colors-hypr.conf

# outputs
# NOTE: there is only a fallback config here. please write your own "monitors.conf" file for whatever device you are using. it is not tracked by git, therefore different configs can exist
# monitor = eDP-1, preferred, 0x0, 1, transform, 0	# laptop display
# monitor = DP-1, 2560x1440@144, 0x0, 1, transform, 0	# desktop display
# monitor = DP-2, preferred, auto, 1, mirror, eDP-1	# mirrored DP2 from eDP1
# monitor = DP-1, 1920x1080@60, -1920x0, 1, transform, 0
source = monitors.conf				# non-tracked monitors file, per-system
monitor = , preferred, auto, auto	# fallback universal config

exec-once=dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

# gsettings
#exec = gsettings set org.gnome.desktop.interface gtk-theme 'Catppuccin-Mocha-Standard-Flamingo-Dark'
exec = gsettings set org.gnome.desktop.interface gtk-theme 'new-horizons'
#exec = gsettings set org.gnome.desktop.interface gtk-theme 'gruvbox-dark-gtk'
#exec = gsettings set org.gnome.desktop.interface icon-theme 'Papirus-Dark'
exec = gsettings set org.gnome.desktop.interface icon-theme 'new-horizons-icons'
exec = gsettings set org.gnome.desktop.wm.preferences button-layout ':close'
exec = gsettings set org.gnome.desktop.interface cursor-theme 'ArcDusk-cursors'
exec = gsettings set org.cinnamon.desktop.default-applications.terminal exec foot

# lock screen when lid close
$swaylock = swaylock -f -e -r --font Papernotes --indicator-radius 80 --indicator-thickness 10 -i $(cat ~/.cache/wal/wal) --effect-blur 15x3
bindl = , switch:on:Lid Switch, exec, $swaylock
bind = SUPER, Home, exec, $swaylock

# WM CONFIG =======================================================

# default env vars.
env = XCURSOR_SIZE,24

input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =

    follow_mouse = 1

    touchpad {
        natural_scroll = true
		disable_while_typing = false
		scroll_factor = 0.5
    }

    sensitivity = 0.1 # -1.0 - 1.0, 0 means no modification.

	touchdevice {
		output = eDP-1
	}
}

general {
    gaps_in = 5
    gaps_out = 15
    border_size = 3
    col.active_border = rgb($color_color1) rgb($color_color3) 45deg
    col.inactive_border = rgb($color_color0)

    layout = dwindle
}

decoration {
    rounding = 7

	blur {
		enabled = true
		size = 3
		passes = 3
	}

    drop_shadow = true
    shadow_range = 4
    shadow_render_power = 3
    col.shadow = rgba(000000af)
}

animations {
    enabled = true

    animation = windows, 1, 5, default
    animation = border, 1, 10, default
    animation = borderangle, 1, 8, default
    animation = fade, 1, 4, default
    animation = workspaces, 1, 3, default, slidevert
}

dwindle {
    pseudotile = true # master switch for pseudotiling
    preserve_split = true # you probably want this
}

master {
    new_is_master = true
}

gestures {
    workspace_swipe = true
	workspace_swipe_fingers = 3
	workspace_swipe_distance = 400
	workspace_swipe_forever = true
}

misc {
	hide_cursor_on_touch = false
	disable_hyprland_logo = true
	background_color = rgb($color_background)
	vfr = false
}

# sourced files =====================================================
source = ~/.config/hypr/rules.conf
source = ~/.config/hypr/keybinds.conf
source = ~/.config/hypr/startup.conf

