#
# window rules file
#

# floating window rules
windowrulev2 = float, class:(steam)
windowrulev2 = float, class:(PrismLauncher)
windowrulev2 = float, class:^(blueman)(.*)$
windowrulev2 = float, class:(pavucontrol)
windowrulev2 = float, class:(nm-connection-editor)
windowrulev2 = float, class:(openrgb)

# xwayland video bridge window hiding
windowrulev2 = opacity 0.0 override 0.0 override,class:^(xwaylandvideobridge)$
windowrulev2 = noanim,class:^(xwaylandvideobridge)$
windowrulev2 = nofocus,class:^(xwaylandvideobridge)$
windowrulev2 = noinitialfocus,class:^(xwaylandvideobridge)$
