#
# window rules file
#

# floating window rules
windowrulev2 = float, class:(steam), title:(Friends)
windowrulev2 = float, class:(steam), title:(Settings)
windowrulev2 = float, class:(PrismLauncher)
windowrulev2 = float, class:^(blueman)(.*)$
windowrulev2 = float, class:(pavucontrol)
windowrulev2 = float, class:(nm-connection-editor)
windowrulev2 = float, class:(openrgb)
windowrulev2 = float, title:(Goober Game)
windowrulev2 = float, title:(Picture-in-Picture)
windowrulev2 = float, title:(vr)
windowrulev2 = float, title:(VR)

# sizing rules
windowrulev2 = minsize 100 100, title:(Goober Game)

# non floating rules
windowrulev2 = tile, class:(Aseprite)

# workspace assignment rules
windowrulev2 = workspace 9, class:(discord)
windowrulev2 = workspace 10, title:(Spotify)
windowrulev2 = workspace 8, class:^(steam_app)
windowrulev2 = workspace 8, class:(Minecraft)

# xwayland video bridge window hiding
windowrulev2 = opacity 0.0 override 0.0 override,class:^(xwaylandvideobridge)$
windowrulev2 = noanim,class:^(xwaylandvideobridge)$
windowrulev2 = nofocus,class:^(xwaylandvideobridge)$
windowrulev2 = noinitialfocus,class:^(xwaylandvideobridge)$

# steam fix?
windowrulev2 = stayfocused, title:^()$,class:^(steam)$
windowrulev2 = minsize 1 1, title:^()$,class:^(steam)$
