#
# startup file
#

# basic shit
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = pipewire-pulse
exec-once = pipewire
exec-once = wireplumber
exec-once = swaybg -i $(cat ~/.cache/wal/wal)
exec-once = blueman-applet
exec-once = eww open bar
exec-once = nm-applet --indicator 
exec-once = openrgb

# gnome polkit
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

# wob
exec-once = rm -f /tmp/wobpipe && mkfifo /tmp/wobpipe
exec-once = tail -f /tmp/wobpipe | wob

# apps
exec-once = /mnt/games/immich_app/start_immich.sh
exec-once = emote

# restore brightness :]
exec-once = brightnessctl set $(cat /tmp/brightness)
