#
# startup file
#

# basic shit
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = pipewire-pulse
exec-once = pipewire
exec-once = wireplumber
exec-once = swaybg -i $(cat ~/.cache/wal/wal)
exec-once = ags
exec-once = openrgb

# gnome polkit
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

# apps
exec-once = emote
exec-once = env QT_QPA_PLATFORM=xcb vktablet
exec-once = nm-applet
exec-once = blueman-applet

# restore brightness :]
exec-once = brightnessctl set $(cat /tmp/brightness)
