#!/bin/sh

toggle_bar() {
    # if first one exits as failed (false), bar isn't open,
    # so it executes the second command, opening bar
    eww close bar || eww open bar
}

toggle_dock() {
    eww close dock || eww open dock
}

toggle_wlsunset() {
    killall wlsunset || wlsunset &
}

toggle_ctrl() {
    CURRENT_STATE=$(eww get ctrl-opened)
    NEW_STATE="true"

    if [[ $CURRENT_STATE == "true" ]]; then
        NEW_STATE="false"
        eww close ctrl-panel
    else
        eww open ctrl-panel
    fi

    eww update ctrl-opened=$NEW_STATE
}

toggle_dashboard() {
    CURRENT_STATE=$(eww get dashboard-opened)
    NEW_STATE="true"

    if [[ $CURRENT_STATE == "true" ]]; then
        NEW_STATE="false"
    fi

    eww update dashboard-opened=$NEW_STATE
}

case "$1" in
    "--toggle-bar")
        toggle_bar
        ;;

    "--toggle-ctrl")
        toggle_ctrl
        ;;

    "--toggle-dashboard")
        toggle_dashboard
        ;;
esac
