#!/bin/sh

# ~~~ functions ~~~

# true if brightness control exists, false if not
# (check if laptop or not more or less)
is_brightness() {
    if command -v brightnessctl &> /dev/null; then
        echo 1  # command exists
    else
        echo 0  # command doesn't
    fi
}

# returns brightness value
get_brightness() {
    echo "$(brightnessctl get -P)"
}

# sets brightness value
set_brightness() {
    brightnessctl set $1
}

BAT=$(ls /sys/class/power_supply | grep BAT | head -n 1)

# returns whether brightnessctl is installed, used for
is_bat() {
    if [[ -z $BAT ]]; then
        echo 0  # no battery
    else
        echo 1  # battery
    fi
}

# returns battery level
get_bat() {
    echo "$(cat /sys/class/power_supply/${BAT}/capacity)"
}

# returns battery icon depending on battery level
get_bat_icon() {
    LEVEL="$(cat /sys/class/power_supply/${BAT}/capacity)%"
    STATUS="$(cat /sys/class/power_supply/${BAT}/status)"

    if [[ $STATUS == "Charging" ]]; then
        OUTPUT="󰂄"
    elif [[ $LEVEL > 90 ]]; then
        OUTPUT="󰁹"  # 100% icon
    elif [[ $LEVEL > 70 ]]; then
        OUTPUT="󰂀"  # 70% icon
    elif [[ $LEVEL > 50 ]]; then
        OUTPUT="󰁾"  # 50% icon
    elif [[ $LEVEL > 30 ]]; then
        OUTPUT="󰁼"  # 30% icon
    elif [[ $LEVEL > 10 ]]; then
        OUTPUT="󰁺"  # 10% icon
    else
        OUTPUT="󱃍"  # 10% or lower, caution indicator
    fi

    echo $OUTPUT
}

# returns current battery status
get_bat_status() {
    echo "$(cat /sys/class/power_supply/${BAT}/status)"
}

# returns volume of default sink
get_vol() {
    echo $(pamixer --get-volume)
}

# returns volume icon depending on volume level
get_vol_icon() {
    VOLUME=$(pamixer --get-volume)
    VOLUME_HUMAN=$(pamixer --get-volume-human)
    DEFAULT_SINK=$(pamixer --get-default-sink)
    OUTPUT=""

    if [[ $VOLUME_HUMAN == "muted" ]]; then
        OUTPUT=""
    elif [[ $DEFAULT_SINK =~ "bluez" ]]; then
        OUTPUT="󰂯"
    elif [[ $VOLUME > 66 ]] || [[ $VOLUME = 100 ]]; then
        OUTPUT=""
    elif [[ $VOLUME > 33 ]]; then
        OUTPUT=""
    else
        OUTPUT=""
    fi

    echo $OUTPUT
}

# toggles mute on default sink
toggle_vol() {
    pamixer -t
}

# returns the status of connection (nmcli-dependent)
get_net_status() {
    echo $(nmcli networking connectivity)
}

# returns an icon depending on current net status
get_net_icon() {
    STATUS=$(nmcli networking connectivity)

    case $STATUS in
        "none")
            echo "󰤮"
            ;;

        "portal")
            echo "󰤩"
            ;;

        "limited")
            echo "󰤩"
            ;;

        "full")
            echo "󰤨"
            ;;

        "unknown")
            echo "󰤫"
            ;;
    esac
}

# ~~~ kslfjdglkdfs ~~~

case "$1" in
    "--is-bat")
        is_bat
        ;;

    "--get-bat")
        get_bat
        ;;

    "--get-bat-icon")
        get_bat_icon
        ;;

    "--get-bat-status")
        get_battery_status
        ;;

    "--is-brightness")
        is_brightness
        ;;

    "--get-brightness")
        get_brightness
        ;;

    "--get-vol")
        get_vol
        ;;

    "--get-vol-icon")
        get_vol_icon
        ;;

    "--get-net-status")
        get_net_status
        ;;

    "--get-net-icon")
        get_net_icon
        ;;
esac
