#!/bin/sh

# ~~~ functions ~~~

get_brightness() {
    echo "$(brightnessctl get -P)"
}

set_brightness() {
    brightnessctl set $1
}

BAT=$(ls /sys/class/power_supply | grep BAT | head -n 1)

get_battery() {
    LEVEL="$(cat /sys/class/power_supply/${BAT}/capacity)"

    echo $LEVEL
}

get_battery_icon() {
    LEVEL="$(cat /sys/class/power_supply/${BAT}/capacity)%"
    STATUS="$(cat /sys/class/power_supply/${BAT}/status)"

    OUTPUT="󰁹"

    if [[ $STATUS == "Charging" ]]; then
        OUTPUT="󰂄"
    elif [[ $LEVEL -gt 90 ]]; then
        OUTPUT="󰂂"
    elif [[ $LEVEL -gt 70 ]]; then
        OUTPUT="󰂀"
    elif [[ $LEVEL -gt 50 ]]; then
        OUTPUT="󰁾"
    elif [[ $LEVEL -gt 30 ]]; then
        OUTPUT="󰁼"
    elif [[ $LEVEL -gt 10 ]]; then
        OUTPUT="󰁺"
    fi

    echo $OUTPUT
}

get_battery_status() {
    STATUS="$(cat /sys/class/power_supply/${BAT}/status)"

    echo $STATUS
}

get_vol() {
    echo $(pamixer --get-volume)
}

get_vol_icon() {
    VOLUME=$(pamixer --get-volume)
    VOLUME_HUMAN=$(pamixer --get-volume-human)
    DEFAULT_SINK=$(pamixer --get-default-sink)
    OUTPUT=""

    if [[ $VOLUME_HUMAN == "muted" ]]; then
        OUTPUT=""
    elif [[ $DEFAULT_SINK =~ "bluez" ]]; then
        OUTPUT="󰂯"
    elif [[ $VOLUME -gt 66 ]]; then
        OUTPUT=""
    elif [[ $VOLUME -gt 33 ]]; then
        OUTPUT=""
    else
        OUTPUT=""
    fi

    echo $OUTPUT
}

toggle_vol() {
    pamixer -t
}

# ~~~ kslfjdglkdfs ~~~

case "$1" in
    "--get-battery")
        get_battery
        ;;

    "--get-battery-icon")
        get_battery_icon
        ;;

    "--get-battery-status")
        get_battery_status
        ;;

    "--get-brightness")
        get_brightness
        ;;

    "--get-vol")
        get_vol
        ;;

    "--get-vol-icon")
        get_vol_icon
        ;;
esac
