#!/usr/bin/env bash

toggle_bar() {
    # if first one exits as failed (false), bar isn't open,
    # so it executes the second command, opening bar
    eww close bar || eww open bar
}

toggle_dock() {
    eww close dock || eww open dock
}

toggle_wlsunset() {
    killall wlsunset || wlsunset &
}

toggle_ctrl() {
    CURRENT_STATE=$(eww get ctrl-opened)
    NEW_STATE="true"

    if [[ $CURRENT_STATE == "true" ]]; then
        NEW_STATE="false"
        eww close ctrl-panel
    else
        eww open ctrl-panel
    fi

    eww update ctrl-opened=$NEW_STATE
}

toggle_dashboard() {
    # open window itself if it's not open and then exit early
    # DASHBOARD_WINDOW=$(eww active-windows | grep "dashboard")
    # if [[ -z $DASHBOARD_WINDOW ]]; then
    #     eww open dashboard
    #     eww update dashboard-opened=true
    #     exit 0
    # fi

    # toggle state of the dashboard-opened variable:
    CURRENT_STATE=$(eww get dashboard-opened)
    if [[ $CURRENT_STATE == "true" ]]; then
        # update variable, wait a second, then close the window
        eww update dashboard-opened=false
        sleep 0.5
        eww close dashboard
    else
        eww open dashboard
        eww update dashboard-opened=true
    fi

}

case "$1" in
    "--toggle-bar")
        toggle_bar
        ;;

    "--toggle-ctrl")
        toggle_ctrl
        ;;

    "--toggle-dashboard")
        toggle_dashboard
        ;;
esac
