#!/bin/sh

# ~~~ functions ~~~

# 0 if process is closed, 1 if running
get_process() {
    PROCESS=$(pgrep -l $1)

    if [ -z "$PROCESS" ]; then
        echo 0
    else
        echo 1
    fi
}

# ~~~ gkwbrkgdfgoiu ~~~

case "$1" in
    "--get-discord")
        get_process Discord
        ;;

    "--kill-discord")
        pkill Discord
        ;;

    "--get-slack")
        get_process slack
        ;;

    "--kill-slack")
        pkill slack
        ;;

    "--get-steam")
        get_process steam
        ;;

    "--kill-steam")
        pkill steam
        ;;
esac
