#!/bin/sh

POLL_INTERVAL="0.1s"

SOCKET_PATH="/tmp/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock"

case "$1" in
    "--get-workspaces")
        socat -u UNIX-CONNECT:$SOCKET_PATH - | while read -r line; do
            hyprctl workspaces -j | jq -c 'sort_by(.id)'
        done
        ;;

    "--get-current-workspace")
        socat -u UNIX-CONNECT:$SOCKET_PATH - | while read -r line; do
            hyprctl activeworkspace -j | jq '.id'
        done
        ;;

    "--set-workspace")
        hyprctl dispatch workspace "$2"
        ;;
esac

# hyprctl workspaces -j | jq -c
