#!/usr/bin/env bash

APPS_PATH="/usr/share/applications"
APPS_PATH_LOCAL="$HOME/.local/share/applications"

# takes output of a cat to the .desktop file and
#   grabs the value of one particular variable within
#
# params:
#   $1 == output of cat from .desktop file
#   $2 == name of variable to grab value from (i.e. "Name" or "Icon")
get_desktop_value() {
    # grab value
    value=$(echo "$1" | grep -e "^$2=.*" | sed "s/^$2=//g")

    # replace double quotes with single quotes
    value=$(echo "$value" | sed "s/\"/\'/g")

    # print output
    echo $value
}

# turns the output of a cat to the
#   .desktop file into json data
#
# params:
#   $1 == output of cat from .desktop file
create_json_desktopentry_data() {
    name=$(get_desktop_value "$1" "Name")
    comment=$(get_desktop_value "$1" "Comment")
    icon=$(get_desktop_value "$1" "Icon")
    categories=$(get_desktop_value "$1" "Categories")

    data+="{"
    data+="\"name\": \"$name\", "
    data+="\"comment\": \"$comment\", "
    data+="\"icon\": \"$icon\","
    data+="\"categories\": \"$categories\""
    data+="}"

    echo $data
}

# creates and prints json data for all .desktop
#   files in the $APPS_PATH variable. needs to be
#   wrapped inside an array outside of the function,
#   isn't inside an array by default
#
# params:
#   $1 == path to search .desktop apps within
get_all_apps_json() {
    lines=$(ls $1)
    output=""

    max_index=$(echo "$lines" | wc -l)
    let "max_index = max_index - 1"

    i=0
    while read -r line; do
        if [[ ! -z $line ]]; then
            file_data=$(cat $1/"$line")
            output+=$(create_json_desktopentry_data "$file_data")

            if [[ $i != $max_index ]]; then
                output+=","
            fi

            let "i = $i + 1"
        fi

    # this is used to keep loop on THIS process
    done <<< $lines

    echo $output
}

# creates an EWW literal
#
# params:
#   $1 == category to filter by (OPTIONAL)
apps_literal() {
    # assemble json array of all app locations
    all_apps_json_nonsort="["
    # all_apps_json_nonsort+=$(get_all_apps_json $APPS_PATH)
    # all_apps_json_nonsort+=", "
    all_apps_json_nonsort+=$(get_all_apps_json $APPS_PATH_LOCAL)
    all_apps_json_nonsort+="]"

    # take prior json array and sort it, then save the de-array'd version
    all_apps_json=$(echo $all_apps_json_nonsort | jq 'sort_by(.name)' | jq -c '.[]')

    #
    # assemble the literal:
    #

    literal="(box :orientation \"v\" "

    while read -r line; do
        name=$(echo "$line" | jq -r ".name")
        icon=$(echo "$line" | jq -r ".icon")
        comment=$(echo "$line" | jq -r ".comment")
        categories=$(echo "$line" | jq -r ".categories")

        # add to literal if there is no category filter...
        #   OR if there IS one and the categories variable
        #   contains said category string
        if [[ ! -z $name ]]; then
            if [[ ! -z $1 ]]; then
                if [[ $categories =~ $1 ]]; then
                    literal+="(app-entry :name \"$name\" :icon \"$icon\" :tooltip \"$comment\") "
                fi
            else
                literal+="(app-entry :name \"$name\" :icon \"$icon\" :tooltip \"$comment\") "
            fi
        fi

    # this is used to keep loop on THIS process
    done <<< "$all_apps_json"

    literal+=")"

    echo $literal
}

apps_literal $1
