#
# window rules file
#

# floating window rules
windowrule = float true, match:class (steam) match:title (Friends List)
windowrule = float true, match:class (steam) match:title (Steam Settings)
windowrule = float true, match:class (PrismLauncher)
windowrule = float true, match:class ^(blueman)(.*)$
windowrule = float true, match:class (pavucontrol)
windowrule = float true, match:class (nm-connection-editor)
windowrule = float true, match:class (org.openrgb.OpenRGB)
windowrule = float true, match:title (Picture-in-Picture)
windowrule = float true, match:title ^.*([Vv][Rr]).*$
windowrule = float true, match:class ^(Mgcb-editor-linux)$
windowrule = float true, match:class ^(xdg-desktop-portal-gtk)$ match:title (Files)
windowrule = float true, match:class ^(Unity)$

# non floating rules
windowrule = float false, match:class (Aseprite)

# workspace assignment rules
windowrule = workspace 7, match:class ([Dd]iscord)
windowrule = workspace 7, match:class (org.telegram.desktop)
windowrule = workspace 7, match:class (vesktop)
windowrule = workspace 8, match:class ([Ss]potify)
windowrule = workspace 6, match:class ([Mm]inecraft)
windowrule = workspace 6, match:fullscreen true
windowrule = workspace 6, match:content 3

# bitwig studio fix, don't focus any window that is thru xwayland and floating
windowrule = no_focus true, match:class (com.bitwig.BitwigStudi) match:xwayland true

